// src/components/ReportExporter.jsx
import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import axios from 'axios';

const API = import.meta.env.VITE_API_BASE_URL;

const ReportExporter = ({ stats }) => {
  if (!stats) return null;

  const handleExport = async () => {
    const doc = new jsPDF();
    const today = new Date();

    // 🏋️ Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Gym Monthly Report', 14, 20);

    doc.setFontSize(12);
    doc.text(`Month: ${today.toLocaleString('default', { month: 'long', year: 'numeric' })}`, 14, 30);
    doc.text(`Generated On: ${today.toLocaleDateString()}`, 14, 37);
    doc.text('--------------------------------------------', 14, 42);

    const { memberStats, financialStats, attendanceStats } = stats;

    // 📊 Member Stats
    autoTable(doc, {
      startY: 50,
      head: [['Member Stats', 'Count']],
      body: [
        ['Total Members', memberStats.totalMembers],
        ['Active Members', memberStats.activeMembers],
        ['Expired Members', memberStats.expiredMembers],
        ['Due Members', memberStats.dueMembers],
      ],
    });

    // 📅 Attendance Stats
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [['Attendance Overview', 'Today']],
      body: [['Daily Check-ins', attendanceStats.dailyAttendanceCount]],
    });

    // 💰 Financial Summary
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [['Financial Overview', 'Amount']],
      body: [['Total Monthly Income', `${financialStats.totalMonthlyIncome.toLocaleString('en-IN')}`]],
    });

    // 🧾 Fetch New Members for this Month
    try {
      const startOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
      const newMembersRes = await axios.get(
        `${API}/api/members/new/${startOfMonth.toISOString()}`
      );
      const newMembers = newMembersRes.data || [];

      // 🎉 New Members Table
      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [['Name', 'Member ID', 'Joined On', 'Plan', 'Contact', 'Payment']],
        body:
          newMembers.length > 0
            ? newMembers.map((m) => [
                m.name,
                m.memberId,
                new Date(m.createdAt).toLocaleDateString(),
                m.planType || '-',
                m.contact || '-',
                m.cashAmountPaid ? m.cashAmountPaid.toLocaleString('en-IN') : '-',
              ])
            : [['No new members this month', '-', '-', '-', '-', '-']],
      });
    } catch (err) {
      console.error('Error fetching new members:', err);
      autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [['New Members This Month']],
        body: [['⚠️ Could not fetch data from backend']],
      });
    }

    // 🧩 Footer
    doc.setFontSize(10);
    doc.text('Generated by Gym Management System', 14, doc.internal.pageSize.height - 10);

    // 💾 Save
    doc.save(`Gym_Report_${today.getMonth() + 1}_${today.getFullYear()}.pdf`);
  };

  return (
    <button
      onClick={handleExport}
      className="mt-4 w-full py-2 bg-indigo-500 hover:bg-indigo-600 text-white rounded-lg transition-colors duration-200"
    >
      Download PDF Report
    </button>
  );
};

export default ReportExporter;
